# This is a basic workflow to help you get started with Actions
name: Create Archive
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'SieuRenPack-1.20.4.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Create or Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 'SieuRenPack-1.20.4'
        files: 'SieuRenPack-1.20.4.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}